[package]
authors = ["bRad <brad@humanenginuity.com>"]
name = "RustQuickstartTemplate"
version = "3.0.0"

[dependencies]

[dependencies.fluent_validator]
git = "https://github.com/humanenginuity/fluent_validator"
optional = false

[profile]

[profile.release]
lto = true
opt-level = 3
